import { StyleSheet, Platform } from "react-native";
import colors from "./colors";

const styles = StyleSheet.create({
  legendContainer: {
    display: "flex",
    justifyContent: "space-evenly",
    alignItems: "center",
    flex: 1,
  },
  legend: {
    width: !Platform.isPad ? "80%" : "60%",
    aspectRatio: 5 / 1,
    marginBottom: 5,
  },
  legendExtra: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: !Platform.isPad ? "80%" : "60%",
    height: "32%",
    backgroundColor: colors.whiteTransparent,
    borderRadius: 15,
  },
  disclamerBtn: {
    width: "42%",
  },
  disclamer: {
    height: "100%",
    aspectRatio: 2.4 / 1,
  },
  screenWrapper: {
    flex: 1,
    position: "relative",
  },
  rewardedWrapper: {
    flex: 1,
    display: "flex",
    alignItems: "center",
  },
  disclamerWrapper: {
    flex: 1,
    display: "flex",
    alignItems: "center",
  },
  discTextWrapper: {
    width: "90%",
    height: "75%",
  },
  discTitle: {
    color: colors.black,
    fontFamily: "NegativeHarmonyBold",
    textAlign: "center",
    fontSize: 22,
    marginTop: "10%",
    marginBottom: "5%",
  },
  discSubTitle: {
    color: colors.black,
    fontFamily: "NegativeHarmonyBold",
    textAlign: "left",
    fontSize: 16,
    marginVertical: 15,
  },
  discContactTitle: {
    color: colors.black,
    fontFamily: "NegativeHarmonyBold",
    textAlign: "left",
    fontSize: 14,
    marginVertical: 15,
  },
  discText: {
    color: colors.black,
    fontFamily: "NegativeHarmonyRegular",
    textAlign: "left",
    fontSize: 14,
  },
  selectWrapper: {
    display: "flex",
    justifyContent: "flex-end",
    height: "12%",
    marginVertical: "5%",
    alignItems: "center",
  },
  selectChordsWrapper: {
    display: "flex",
    justifyContent: "flex-end",
    height: "20%",
    marginVertical: "5%",
  },
  selectTextExp: {
    color: colors.black,
    fontFamily: "NegativeHarmonyRegular",
    textAlign: "center",
    fontSize: 14,
    marginVertical: 10,
  },
  selectInput: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "60%",
    height: 30,
    marginVertical: 10,
    marginHorizontal: "20%",
    backgroundColor: colors.whiteTransparent,
    borderWidth: 0,
    borderRadius: 30,
  },
  selectInputText: {
    fontFamily: "NegativeHarmonyRegular",
    color: colors.black,
    textAlign: "center",
    fontSize: 14,
  },
  selectListWrapper: {
    borderRadius: 30,
    marginBottom: "30%",
    marginHorizontal: "5%",
    marginTop: "15%",
    overflow: Platform.OS == "ios" ? "scroll" : "hidden",
    width: "90%",
  },
  selectList: {
    backgroundColor: colors.white,
    borderColor: colors.blue,
    borderRadius: 30,
    borderWidth: 2,
    flexGrow: 1,
    width: "100%",
  },
  selectItem: {
    width: "100%",
    borderBottomColor: colors.blueTransparent,
    borderBottomWidth: 1,
  },
  selectItemNoBorder: {
    borderBottomWidth: 0,
  },
  selectDisabledText: {
    fontFamily: "NegativeHarmonyRegular",
    textAlign: "center",
    fontSize: 18,
    marginVertical: 10,
  },
  selectText: {
    fontFamily: "NegativeHarmonyRegular",
    textAlign: "center",
    fontSize: 18,
    marginVertical: 10,
  },
  selectListArrow: {
    position: "absolute",
    right: 14,
    width: 10,
    aspectRatio: 1 / 1,
  },
  circleWrapper: {
    flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  icon: {
    position: "absolute",
    marginVertical: "22%",
    left: "40%",
    width: "20%",
    aspectRatio: 1 / 1,
    zIndex: 4,
  },
  circleKeys: {
    width: "100%",
    aspectRatio: 1 / 1,
    zIndex: 3,
  },
  scaleSpace: {
    height: "32%",
    width: "100%",
    position: "relative",
  },
  scaleWrapper: {
    position: "absolute",
    left: "-5%",
    justifyContent: "flex-start",
    width: "110%",
    bottom: "-15%",
    height: "100%",
    backgroundColor: colors.white,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    paddingTop: Platform.OS == "ios" && !Platform.isPad ? 10 : 5,
    paddingBottom: "17%",
    paddingLeft: 20,
    paddingRight: 20,
    zIndex: 1,
    elevation: 0,
  },
  positiveScale: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "flex-end",
    height: "26%",
  },
  negativeScale: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "flex-start",
    height: "26%",
  },
  positiveScaleText: {
    fontFamily: "NegativeHarmonyBold",
    fontSize: 15,
    width: 30,
    textAlign: "center",
    color: colors.positiveText,
  },
  negativeScaleText: {
    fontFamily: "NegativeHarmonyBold",
    fontSize: 15,
    width: 30,
    textAlign: "center",
    color: colors.negativeText,
  },
  axisLegend: {
    width: "100%",
    height: 6,
    borderRadius: 6,
    marginTop: 10,
    marginBottom: 10,
    backgroundColor: colors.blue,
  },
  selectedScaleNameWrapper: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "baseline",
    paddingVertical: 10,
  },
  selectedScaleKey: {
    fontFamily: "NegativeHarmonyBold",
    color: colors.white,
    fontSize: 32,
    marginRight: 3,
  },
  selectedScaleName: {
    fontFamily: "NegativeHarmonyBold",
    color: colors.black,
    fontSize: 16,
    textTransform: "lowercase",
    marginLeft: 3,
  },
  chordsWrapper: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  rewardedOpen: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.blue,
    width: "75%",
    height: 70,
    borderRadius: 35,
  },
  rewardedOpenText: {
    color: colors.white,
    textAlign: "center",
    fontFamily: "NegativeHarmonyBold",
    fontSize: 18,
  },
  scrollChords: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    borderRadius: 30,
    backgroundColor: colors.white,
  },
  scrollChordsExpText: {
    fontFamily: "NegativeHarmonyRegular",
    fontSize: 14,
    textAlign: "center",
    color: colors.black,
    marginVertical: 10,
  },
  scrollChordsWrapper: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
  },
  scrollChordsSpace: {
    height: 90,
    backgroundColor: colors.black,
  },
  scrollChordsNoteSelected: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 90,
    aspectRatio: 1 / 1,
    marginHorizontal: 10,
    borderRadius: 90,
    backgroundColor: colors.blue,
  },
  scrollChordsNote: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 90,
    aspectRatio: 1 / 1,
    marginHorizontal: 10,
    borderRadius: 90,
    borderWidth: 4,
    borderColor: colors.blue,
    backgroundColor: colors.white,
  },
  scrollChordsNoteTextSelected: {
    fontFamily: "NegativeHarmonyBold",
    fontSize: 22,
    width: 44,
    textAlign: "center",
    color: colors.white,
  },
  scrollChordsNoteText: {
    fontFamily: "NegativeHarmonyBold",
    fontSize: 22,
    width: 44,
    textAlign: "center",
    color: colors.blue,
  },
  scaleNameWrapper: {
    alignItems: "baseline",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    paddingVertical: 10,
  },
  exit: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 25,
    aspectRatio: 1 / 1,
  },
  exitDisabled: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 25,
    aspectRatio: 1 / 1,
  },
  rewardedExp: {
    marginTop: "30%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  rewardedExpText: {
    color: colors.black,
    textAlign: "center",
    fontFamily: "NegativeHarmonyBold",
    fontSize: 24,
    marginVertical: 2,
  },
  rewardedStart: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.blue,
    width: "75%",
    height: 70,
    borderRadius: 35,
    marginTop: 60,
    marginBottom: 30,
  },
  rewardedDisabled: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.disabled,
    width: "75%",
    height: 70,
    borderRadius: 35,
    marginTop: 60,
    marginBottom: 30,
  },
  rewardedStartText: {
    color: colors.white,
    textAlign: "center",
    fontFamily: "NegativeHarmonyBold",
    fontSize: 20,
  },
  rewardedDisc: {
    color: colors.black,
    textAlign: "center",
    fontFamily: "NegativeHarmonyRegular",
    fontSize: 12,
  },
});

export default styles;
